package status

const (
	OK                         = int64(0)       // No error has occurred
	Timeout                    = int64(-7)      // For proxy (handles 504) - not used in Outrun
	OtherError                 = int64(-8)      // Misc. error
	NotReachable               = int64(-10)     // For proxy (handles 502) - not used in Outrun
	InvalidResponse            = int64(-20)     // ???
	ClientError                = int64(-400)    // Used in Outrun, but this can be returned client-side if the game detects an HTTP 4xx response
	InternalServerError        = int64(-500)    // Used in Outrun, but this can be returned client-side if the game detects an HTTP 5xx response
	HSPPurchaseError           = int64(-600)    // Not used in Outrun
	ServerBusy                 = int64(-700)    // Not used in Outrun
	RequestParamError          = int64(-10100)  // Malformed request param
	NotAvailablePlayer         = int64(-10101)  // Purpose unknown
	MissingPlayer              = int64(-10102)  // Player does not exist in database
	ExpiredSession             = int64(-10103)  // Typically sent when the session has expired. This isn't handled correctly in any official versions of Runners.
	InvalidPassword            = int64(-10104)  // Returned during login when the password is not valid for that account
	InvalidSerialCode          = int64(-10105)  // Invite code not valid
	UsedSerialCode             = int64(-10106)  // Invite code already used
	HSPWebAPIError             = int64(-10115)  // HSP API error; not used in Outrun
	ApolloWebAPIError          = int64(-10115)  // Sega Networks Apollo API error; not used in Outrun
	MasterDataMismatch         = int64(-10121)  // Purpose unknown; possibly synonymous with DataMismatch?
	NotStartEvent              = int64(-10201)  // The sent event has not started yet
	AlreadyEndEvent            = int64(-10202)  // The sent event has ended
	AlreadyExistedPrePurchase  = int64(-11001)  // IAP error; not used in Outrun
	AlreadyRemovedPrePurchase  = int64(-11002)  // IAP error; not used in Outrun
	InvalidReceiptData         = int64(-11003)  // IAP error; not used in Outrun
	AlreadyProcessedReceipt    = int64(-11004)  // IAP error; not used in Outrun
	ServerSecurityError        = int64(-19001)  // Purpose unknown
	VersionDifference          = int64(-19002)  // Brings up "update sonic runners" message; intended for no-longer-supported clients
	DecryptionFailure          = int64(-19003)  // Could not decrypt param, possibly due to data corruption
	ParamHashDifference        = int64(-19004)  // Purpose unknown
	ServerNextVersion          = int64(-19990)  // Shows a special maintenance message based on text strings returned alongside it
	ServerMaintenance          = int64(-19997)  // Not used in Outrun; returned by 503 handler script
	ServerBusyError            = int64(-19998)  // Not used in Outrun
	ServerSystemError          = int64(-19999)  // Not used in Outrun
	NotEnoughRings             = int64(-20131)  // Not enough rings to perform action
	NotEnoughEnergy            = int64(-20132)  // Not enough revive tokens to perform action
	AlreadyUsedDailyRevive     = int64(-20133)  // Daily revive already used
	CharacterLevelLimit        = int64(-20601)  // Character is already maxed out
	AllChaoLevelLimit          = int64(-20602)  // All chao are already maxed out
	EnergyLimitPurchaseTrigger = int64(-21010)  // ???
	NotEnoughRedRings          = int64(-21030)  // Not enough red rings to perform action
	DataMismatch               = int64(-30120)  // Used to possibly indicate a desync?
	RouletteUseLimit           = int64(-30401)  // Returned when attempting to use the roulettes when you do not have any red star rings or roulette tickets
	RouletteBoardReset         = int64(-30411)  // Not used in Outrun (yet); attempting to spin the roulette when the board is past its end time
	AlreadyInvitedFriend       = int64(-30801)  // Friend functionality; TBD
	AlreadyRequestedEnergy     = int64(-30901)  // Friend functionality; TBD
	AlreadySentEnergy          = int64(-30902)  // Friend functionality; TBD
	ReceiveFailureMessage      = int64(-30910)  // Error occurred while accepting gifts from gift box
	VersionForApplication      = int64(-999002) // Sets Runners to use last URL in the list
)
