package status

const (
	OK                         = int64(0)       // no error has occurred
	Timeout                    = int64(-7)      // for proxy (handles 504) - not used in outrun
	OtherError                 = int64(-8)      // misc. error
	NotReachable               = int64(-10)     // for proxy (handles 502) - not used in outrun
	InvalidResponse            = int64(-20)     // ???
	ClientError                = int64(-400)    // used in outrun, but typically an internal error code
	InternalServerError        = int64(-500)    // used in outrun, but typically an internal error code
	HSPPurchaseError           = int64(-600)    // ???
	ServerBusy                 = int64(-700)    // not used in outrun
	RequestParamError          = int64(-10100)  // malformed request param
	NotAvailablePlayer         = int64(-10101)  // ???
	MissingPlayer              = int64(-10102)  // player does not exist in database
	ExpiredSession             = int64(-10103)  // not sure what this is for; it just retries the request if this is given
	InvalidPassword            = int64(-10104)  // returned during login when the password is not valid for that account
	InvalidSerialCode          = int64(-10105)  // invite code not valid
	UsedSerialCode             = int64(-10106)  // invite code already used
	HSPWebAPIError             = int64(-10115)  // ???
	ApolloWebAPIError          = int64(-10115)  // Sega Apollo API error; not used in Outrun
	MasterDataMismatch         = int64(-10121)  // ???
	NotStartEvent              = int64(-10201)  // event has not started yet
	AlreadyEndEvent            = int64(-10202)  // event has ended
	AlreadyExistedPrePurchase  = int64(-11001)  // iap error; not used in outrun
	AlreadyRemovedPrePurchase  = int64(-11002)  // iap error; not used in outrun
	InvalidReceiptData         = int64(-11003)  // iap error; not used in outrun
	AlreadyProcessedReceipt    = int64(-11004)  // iap error; not used in outrun
	ServerSecurityError        = int64(-19001)  // ???
	VersionDifference          = int64(-19002)  // brings up "update sonic runners" message; intended for no-longer-supported clients
	DecryptionFailure          = int64(-19003)  // could not decrypt param, possibly due to data corruption
	ParamHashDifference        = int64(-19004)  // ???
	ServerNextVersion          = int64(-19990)  // shows a special maintenance message based on text strings returned alongside it
	ServerMaintenance          = int64(-19997)  // not used in outrun; returned by 503 handler script
	ServerBusyError            = int64(-19998)  // ???
	ServerSystemError          = int64(-19999)  // ???
	NotEnoughRings             = int64(-20131)  // not enough rings to perform action
	NotEnoughEnergy            = int64(-20132)  // not enough revive tokens to perform action
	CharacterLevelLimit        = int64(-20601)  // character is already maxed out
	AllChaoLevelLimit          = int64(-20602)  // all chao are already maxed out
	EnergyLimitPurchaseTrigger = int64(-21010)  // ???
	NotEnoughRedRings          = int64(-21030)  // not enough red rings to perform action
	DataMismatch               = int64(-30120)  // used to possibly indicate a desync?
	RouletteUseLimit           = int64(-30401)  // returned when attempting to use the roulettes when you do not have any red star rings or roulette tickets
	RouletteBoardReset         = int64(-30411)  // not used in outrun (yet); attempting to spin the roulette when the board is past its end time
	AlreadyInvitedFriend       = int64(-30801)  // friend functionality
	AlreadyRequestedEnergy     = int64(-30901)  // friend functionality
	AlreadySentEnergy          = int64(-30902)  // friend functionality
	ReceiveFailureMessage      = int64(-30910)  // error occurred while receiving gifts from gift box
	VersionForApplication      = int64(-999002) // sets Runners to use last URL in the list
)
